language: node_js

sudo: false

node_js:
    - "16"

cache:
    apt: true
    directories:
        - node_modules

env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
    ssh_known_hosts: github.com

before_script:
    - export TZ='Asia/Shanghai'
    - git config --global user.name "fatedier"
    - git config --global user.email "fatedier@gmail.com"
    - git config --global push.default simple

script:
    - git checkout master
    #- npm install --no-optional
    - chmod 755 ./deploy.sh && ./deploy.sh
    - chmod 755 ./generate.sh && ./generate.sh

after_script:
    - git add -A ./docs/
    - git commit -am "Auto deploy by travis-ci."
    - git push --force --quiet "https://${GH_TOKEN}@github.com/gofrp/frp-site.git" master:master
